---
title: "Dygraphs"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
library(dygraphs)
library(flexdashboard)
```

Row
-------------------------------------

### Articles

```{r}
library(flexdashboard)
articles <- 125
valueBox(articles, icon = "fa-pencil")
```

### Comments

```{r}
comments <- 22
valueBox(comments, icon = "fa-comments")
```

### Spam

```{r}
spam <- 44
valueBox(spam, 
         icon = "fa-trash",
         color = ifelse(spam > 10, "warning", "primary"))
```

Row
-------------------------------------


### Contact Rate

```{r}
gauge(65, min = 0, max = 100, symbol = '%', gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
```

### Average Rating

```{r}
gauge(45, min = 0, max = 50, gaugeSectors(
  success = c(41, 50), warning = c(21, 40), danger = c(0, 20)
))
```

### Cancellations

```{r}
gauge(7, min = 0, max = 10, gaugeSectors(
  success = c(0, 2), warning = c(3, 6), danger = c(7, 10)
))
```

